# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-14 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='Hotel',
            new_name='hotel',
        ),
        migrations.AddField(
            model_name='customer',
            name='mail',
            field=models.CharField(default='', max_length=100),
        ),
    ]
