# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-14 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20201014_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata', models.CharField(max_length=100)),
                ('name_f', models.CharField(max_length=100)),
                ('latitude', models.FloatField(max_length=100)),
                ('longitude', models.FloatField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='customer',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='mail',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
