# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-14 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20201014_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='reservation.Airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origins', to='reservation.Airport')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.Customer')),
            ],
        ),
    ]
