# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-14 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_flight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='iata',
            new_name='airport',
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='name_f',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='owner',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='longitude',
        ),
    ]
