# Generated by Django 3.1.1 on 2020-10-15 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20201014_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='customer',
        ),
        migrations.AddField(
            model_name='reservation',
            name='airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.airport'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.flight'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='airport',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin',
            field=models.CharField(max_length=100),
        ),
    ]
