# Generated by Django 3.1.1 on 2020-10-16 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_hotel_price_net_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='mail',
            new_name='email',
        ),
    ]
